CREATE DATABASE IF NOT EXISTS `${db.schema}`;
USE `${db.schema}`;

CREATE TABLE IF NOT EXISTS `teams` (
`id` VARCHAR(128) DEFAULT NULL,
`owner_name` VARCHAR(128) DEFAULT NULL,
`name` VARCHAR(128) DEFAULT NULL,
`document` LONGTEXT DEFAULT NULL,
`created_on` BIGINT DEFAULT NULL,
`modified_on` BIGINT DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `players` (
`id` VARCHAR(128) DEFAULT NULL,
`name` VARCHAR(128) DEFAULT NULL,
`price` INT(10) DEFAULT NULL,
`document` LONGTEXT DEFAULT NULL,
`created_on` BIGINT DEFAULT NULL,
`modified_on` BIGINT DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB;

commit;
