version: '3'
services:
  db:
    build:
      context: ./${PROJECT_MODULE_DIR}/src/main/resources/META-INF/docker/db
    volumes:
      - data:/var/lib/mysql
  app:
    depends_on:
      - db
    image: jetty
    environment:
      - env=local_docker
    ports:
      - ${WEBAPP_PORT}:8080
    links:
      - db
    volumes:
      - "./${PROJECT_MODULE_DIR}/target/${COMPOSE_PROJECT_NAME}-${PROJECT_MODULE_DIR}-${PROJECT_VERSION}.war:/var/lib/jetty/webapps/${WEBAPP_CONTEXT_PATH}.war"
volumes:
  data: